import type { GetServerSideProps, NextPage } from 'next'
import { getSession, signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  const { data: session } = useSession()
  return (
    <div className="">
      <Head>
        <title>Blog App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {session ? (
          <div>
            <h1>{session.user.name}</h1>
            <h3>{session.user.email}</h3>
            <h2>{session.user.role}</h2>
            <h1>{session.user.id}</h1>
            <Image
              className="rounded-full"
              src={session.user.image as string}
              alt={session.user.name}
              height="40px"
              width="40px"
            />
            <button
              onClick={() => {
                signOut()
              }}
            >
              Sign Out
            </button>
          </div>
        ) : (
          <button
            onClick={() => {
              signIn('google')
            }}
          >
            Sign In
          </button>
        )}
        <h1></h1>
      </div>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const session = await getSession({ ctx })
  return {
    props: { session },
  }
}
